version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2

# setup
commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - setup
  test:
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/mysql:8-ram
        name: "db"
        environment:
          MYSQL_USER: root
          MYSQL_DB: myapp_test
          MYSQL_ROOT_PASSWORD: password
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
      RAILS_ENV: test
    steps:
      - setup
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
